version: "3.9" # specify version in case docker compose changes syntax

services:
  app: # name of our service
    build:
      context: . # build dockerfile inside current dir
      args:
        - DEV=true # we're using this compose file to build a dev image, so set a DEV arg to true
    ports:
      - "8000:8000" # maps point 8000 on our machine to port 8000 inside our docker container
    volumes:
      # map directories from our system into the docker container, so that updates to our code
      # are reflected in container in real time without rebuild
      - ./app:/app
    # command to run the service (default, can be overriden in dockerfile)
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment: # for dev setup only, obv don't hardcode for a real setup
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

  db:
    # local dev db setup, not for prod/server deployment
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment: # set env vars for initial database service configuration
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

volumes:
  dev-db-data:
      
